<a href="https://colab.research.google.com/github/ulyazzh/Latihan_STKI/blob/main/Tugas3_STKI/Latihan3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [17]:
import numpy as np
np.random.seed(42)
v_revenge = np.array([1,0,1,0,1,0,1])
print(v_revenge)

weight = np.random.random_sample((7,4))
print(weight)


hidden_layer_sg = np.dot(v_revenge,weight)
print(hidden_layer_sg)

weight_prime = np.random.random_sample((4,7))
print(weight_prime)

o_the = np.dot(hidden_layer_sg, weight_prime)
print(o_the)


[1 0 1 0 1 0 1]
[[0.37454012 0.95071431 0.73199394 0.59865848]
 [0.15601864 0.15599452 0.05808361 0.86617615]
 [0.60111501 0.70807258 0.02058449 0.96990985]
 [0.83244264 0.21233911 0.18182497 0.18340451]
 [0.30424224 0.52475643 0.43194502 0.29122914]
 [0.61185289 0.13949386 0.29214465 0.36636184]
 [0.45606998 0.78517596 0.19967378 0.51423444]]
[1.73596736 2.96871928 1.38419724 2.37403191]
[[0.59241457 0.04645041 0.60754485 0.17052412 0.06505159 0.94888554
  0.96563203]
 [0.80839735 0.30461377 0.09767211 0.68423303 0.44015249 0.12203823
  0.49517691]
 [0.03438852 0.9093204  0.25877998 0.66252228 0.31171108 0.52006802
  0.54671028]
 [0.18485446 0.96958463 0.77513282 0.93949894 0.89482735 0.59789998
  0.92187424]]
[3.91476802 4.54545281 3.54303172 5.47478208 3.97543493 4.14884193
 6.09166064]


In [18]:
v_the = np.array([1,0,1,0,1,0,1])
print(v_the)

hidden_layer_cbow = np.dot(v_the,weight)
print(hidden_layer_cbow)

o_revenge = np.dot(hidden_layer_cbow, weight_prime)
print(o_revenge)


[1 0 1 0 1 0 1]
[1.73596736 2.96871928 1.38419724 2.37403191]
[3.91476802 4.54545281 3.54303172 5.47478208 3.97543493 4.14884193
 6.09166064]
